from PIL import Image, ImageFilter

img = Image.open('./scripting/image-playground/Pokedex/pikachu.jpg')
# filtered_img = img.filter(ImageFilter.BLUR)
# filtered_img.save('./scripting/image-playground/Pokedex/blurred.png')
# filtered_img = img.filter(ImageFilter.SMOOTH)
# filtered_img.save('./scripting/image-playground/Pokedex/smooth.png')
filtered_img = img.convert('L')
filtered_img = filtered_img.rotate(90)
filtered_img = filtered_img.resize((300, 300))
filtered_img = filtered_img.crop((100, 100, 400, 400))
filtered_img.save('./scripting/image-playground/Pokedex/grey.png')
# print(img.size)
# print(img.format)
# print(img.mode)
# print(img.palette)
# print(img.info)
# print(img.getpixel((0, 0)))
# print(img.getpixel((0, 0)))
filtered_img.show()